# File: ansible-role-bashrc-custom-manager/tasks/main.yml
---
- name: Manage custom bashrc configuration
  tags:
    - configuration
    - bashrc
  block:
    - name: "Check if custom bashrc exists for user {{ source_user ~ ' and ' ~ source_host }}"
      ansible.builtin.stat:
        path: "{{ source_home }}/{{ bashrc_custom }}"
      register: custom_bashrc_stat
      delegate_to: "{{ source_host }}"
      run_once: true

    - name: "Create sample custom bashrc for {{ source_user ~ ' user on ' ~ source_host ~ ' host'}}"
      ansible.builtin.copy:
        dest: "{{ source_home }}/{{ bashrc_custom }}"
        content: |
          # Test custom bashrc content
          alias ll='ls -la'
          alias h='history'
        mode: '0644'
        owner: "{{ source_user }}"
        group: "{{ source_user }}"
      delegate_to: "{{ source_host }}"
      run_once: true
      check_mode: false
      when: not custom_bashrc_stat.stat.exists

    - name: "Fetch custom bashrc from {{ source_user ~ ' user on ' ~ source_host ~ ' host'}}"
      ansible.builtin.slurp:
        src: "{{ source_home }}/{{ bashrc_custom }}"
      register: custom_bashrc_content
      delegate_to: "{{ source_host }}"
      run_once: true

    - name: "Copy custom bashrc to {{ target_user ~ ' user on target hosts'}}"
      ansible.builtin.copy:
        content: "{{ custom_bashrc_content['content'] | b64decode }}"
        dest: "{{ target_home }}/{{ bashrc_custom }}"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'
      when: inventory_hostname != source_host or target_user != source_user

    - name: Ensure proper file permissions on bashrc for user {{ target_user }}
      ansible.builtin.file:
        path: "{{ target_home }}/{{ bashrc }}"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'
      when: inventory_hostname != source_host or target_user != source_user

    - name: "Create bashrc file with correct permissions for user {{ target_user }}"
      ansible.builtin.copy:
        dest: "{{ target_home }}/{{ bashrc }}"
        content: ""
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'
        force: false

    - name: "Add custom bashrc source to {{ bashrc ~ ' for user ' ~ target_user }}"
      when: inventory_hostname != source_host or target_user != source_user
      register: update_bashrc
      ansible.builtin.blockinfile:
        path: "{{ target_home }}/{{ bashrc }}"
        block: |
          # Source custom bashrc configuration
          if [ -f "$HOME/{{ bashrc_custom }}" ]; then
              source "$HOME/{{ bashrc_custom }}"
          fi
        marker: "# {mark} MANAGED BY ANSIBLE ROLE: bashrc-custom-manager"
        state: present
        create: true

    - name: "Apply correct permissions on bashrc for user {{ target_user }}"
      ansible.builtin.file:
        path: "{{ target_home }}/{{ bashrc }}"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'
